// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // 🔥 ANDROID CONFIG (REQUIRED)
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'YOUR_ANDROID_API_KEY',
    appId: 'YOUR_ANDROID_APP_ID',
    messagingSenderId: '765023326225',
    projectId: 'celebreats-7f607',
    storageBucket: 'celebreats-7f607.firebasestorage.app',
  );

  // 🌐 WEB CONFIG
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxlrikNVAhTk8CVAaisAbiTLEwWgHop78',
    appId: '1:765023326225:web:492282c28d423f0fb4a1b0',
    messagingSenderId: '765023326225',
    projectId: 'celebreats-7f607',
    authDomain: 'celebreats-7f607.firebaseapp.com',
    storageBucket: 'celebreats-7f607.firebasestorage.app',
    measurementId: 'G-G3XVMLG4ML',
  );

  // 🍎 IOS CONFIG
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkIkgzHDX4la0WvNhzdVCRZ0Ax_nCc04Q',
    appId: '1:765023326225:ios:acc3af4220daad0ab4a1b0',
    messagingSenderId: '765023326225',
    projectId: 'celebreats-7f607',
    storageBucket: 'celebreats-7f607.firebasestorage.app',
    iosBundleId: 'com.example.celebreats',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkIkgzHDX4la0WvNhzdVCRZ0Ax_nCc04Q',
    appId: '1:765023326225:ios:acc3af4220daad0ab4a1b0',
    messagingSenderId: '765023326225',
    projectId: 'celebreats-7f607',
    storageBucket: 'celebreats-7f607.firebasestorage.app',
    iosBundleId: 'com.example.celebreats',
  );
}
